//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softblue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musica
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Album { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Genero { get; set; }
        public string Cantor { get; set; }
    }
}
