//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Nota> Nota { get; set; }
    }
}
