//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int id { get; set; }
        public string materia { get; set; }
        public double valor { get; set; }
    
        public virtual Aluno Aluno { get; set; }
    }
}
